PS C:\Django\myproject> pwd

Path
----
C:\Django\myproject


PS C:\Django\myproject> cd crud\models.py
cd : パス 'crud\models.py' が存在しないため検出できません。
発生場所 行:1 文字:1
+ cd crud\models.py
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (crud\models.py:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Django\myproject> cd crud
PS C:\Django\myproject\crud> cd models.py
cd : パス 'models.py' が存在しないため検出できません。
発生場所 行:1 文字:1
+ cd models.py
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (models.py:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Django\myproject\crud> pwd

Path
----
C:\Django\myproject\crud


PS C:\Django\myproject\crud> python manage.py migrate
>>
C:\Users\fl-nanba21\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Django\\myproject\\crud\\manage.py': [Errno 2] No such file or directory
PS C:\Django\myproject\crud> python manage.py runserver
>>
C:\Users\fl-nanba21\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Django\\myproject\\crud\\manage.py': [Errno 2] No such file or directory
PS C:\Django\myproject\crud> history 0
Get-History : パラメーター 'Id の引数を確認できません。引数 0 が、最小許容範囲 1 を下回っています。1 以上の引数を指定して、コマンドを再度実行してください。
発生場所 行:1 文字:9
+ history 0
+         ~
    + CategoryInfo          : InvalidData: (:) [Get-History]、ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetHistoryCommand

PS C:\Django\myproject\crud> history  

  Id CommandLine
  -- -----------
   1 try { . "c:\Users\fl-nanba21\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps...
   2 pwd
   3 cd crud\models.py
   4 cd crud
   5 cd models.py
   6 pwd
   7 python manage.py migrate...
   8 python manage.py runserver...
   9 history 0


PS C:\Django\myproject\crud> 
 *  履歴が復元されました 


#ここからスタート

PS C:\Django\myproject> python manage.py runserver
>> 
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2024 - 23:02:28
Django version 5.1.3, using settings 'myproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[18/Nov/2024 23:02:38] "GET /admin/ HTTP/1.1" 200 6804
[18/Nov/2024 23:02:38] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[18/Nov/2024 23:02:38] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0

